### ISSUE TITLE
Extension slows down page

### ISSUE THREAD

**Issue by c0bras** [c0bras/DarkCloud#1]
The extension slows down the SoundCloud page usually when music is playing, and it has to do with how it loads the CSS code.
I'm looking for contributions that might fix this problem!

Thank you!

**Comment by danfelix** [comment]
Pretty the sure problem, or at least **a** problem, is that the DOMNodeRemoved event fires a lot (30+ times) and the script inserts a new CSS <link /> every time the event fires.

I can take a stab at fixing it, should I just fork and create a 1.0.3 folder?
